apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-app
        image: ankit2222/rescueradarauth:v1.2
        ports:
        - containerPort: 8000
        # env:
          # - name: 
            # value: 
       
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"