apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: LoadBalancer
  selector:
    app: login-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31110